batch_size: 256
max_epochs: 1
learning_rate: 1e-3
weight_decay: 0.01
accelerator: gpu # cpu or gpu
devices: 1 # GPUの数
num_workers: 4 # DataLoaderのワーカー数
val_check_interval: 1.0 # 1.0はエポックごとに検証
log_every_n_steps: 50
