batch_size: 64
max_epochs: 5
learning_rate: 1e-5
weight_decay: 0.01
accelerator: gpu # cpu or gpu
devices: 1 # GPUの数
num_workers: 0 # DataLoaderのワーカー数
val_check_interval: 1.0 # 1.0はエポックごとに検証
log_every_n_steps: 50
